CREATE OR REPLACE PROCEDURE UT_DE_FRAMEWORK{{ENV}}.BASE.SP_FULL_LOAD_REGION_ANALYTICS()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS '
BEGIN
    -- 1. Create or replace the base table by joining raw tables.
    EXECUTE IMMEDIATE ''
      CREATE OR REPLACE TABLE UT_DE_FRAMEWORK.BASE.REGION_ANALYTICS_BASE AS
      WITH joined_data AS (
         SELECT
            r.R_REGIONKEY,
            r.R_NAME          AS REGION_NAME,
            r.R_COMMENT       AS REGION_COMMENT,
            n.N_NATIONKEY,
            n.N_NAME          AS NATION_NAME,
            c.C_CUSTKEY,
            c.C_NAME          AS CUSTOMER_NAME,
            o.O_ORDERKEY,
            o.O_ORDERDATE,
            o.O_TOTALPRICE,
            SUM(l.L_QUANTITY)       AS TOTAL_QUANTITY,
            SUM(l.L_EXTENDEDPRICE)  AS TOTAL_EXTENDEDPRICE
         FROM UT_DE_FRAMEWORK.RAW.REGION r
         JOIN UT_DE_FRAMEWORK.RAW.NATION n ON n.N_REGIONKEY = r.R_REGIONKEY
         JOIN UT_DE_FRAMEWORK.RAW.CUSTOMER c ON c.C_NATIONKEY = n.N_NATIONKEY
         JOIN UT_DE_FRAMEWORK.RAW.ORDERS o ON o.O_CUSTKEY = c.C_CUSTKEY
         JOIN UT_DE_FRAMEWORK.RAW.LINEITEM l ON l.L_ORDERKEY = o.O_ORDERKEY
         GROUP BY
            r.R_REGIONKEY, r.R_NAME, r.R_COMMENT,
            n.N_NATIONKEY, n.N_NAME,
            c.C_CUSTKEY, c.C_NAME,
            o.O_ORDERKEY, o.O_ORDERDATE, o.O_TOTALPRICE
      )
      SELECT * FROM joined_data
    '';

    -- 2. Create or replace the reporting view for region analytics.
    EXECUTE IMMEDIATE ''
      CREATE OR REPLACE VIEW UT_DE_FRAMEWORK.REPORTING.REGION_ANALYTICS_REPORT AS
      SELECT
         REGION_NAME,
         NATION_NAME,
         COUNT(DISTINCT CUSTOMER_NAME) AS TOTAL_CUSTOMERS,
         COUNT(DISTINCT O_ORDERKEY) AS TOTAL_ORDERS,
         SUM(O_TOTALPRICE) AS TOTAL_REVENUE,
         SUM(TOTAL_QUANTITY) AS TOTAL_QUANTITY,
         SUM(TOTAL_EXTENDEDPRICE) AS TOTAL_EXTENDEDPRICE
      FROM UT_DE_FRAMEWORK.BASE.REGION_ANALYTICS_BASE
      GROUP BY REGION_NAME, NATION_NAME
    '';

    RETURN ''Full load for region analytics completed successfully.'';
END;
';