CREATE OR REPLACE PROCEDURE UT_DE_FRAMEWORK{{ENV}}.BASE.FACT_LINEITEM()
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS CALLER
AS '
    BEGIN
    MERGE INTO UT_DE_FRAMEWORK.BASE.FACT_LINEITEM target
    USING (
	WITH final AS (
    SELECT 
        L_ORDERKEY, 
        L_PARTKEY, 
        L_SUPPKEY, 
        L_LINENUMBER, 
        L_QUANTITY, 
        L_EXTENDEDPRICE, 
        L_DISCOUNT, 
        L_TAX, 
        L_RETURNFLAG, 
        L_LINESTATUS, 
        L_SHIPDATE, 
        L_COMMITDATE, 
        L_RECEIPTDATE, 
        L_SHIPINSTRUCT, 
        L_SHIPMODE, 
        L_COMMENT
    FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
    WHERE L_SHIPDATE BETWEEN ''1995-01-01'' AND ''1995-12-31''  -- Filter by ship date in 1995
)

SELECT 
    L_ORDERKEY, 
    L_PARTKEY, 
    L_SUPPKEY, 
    L_LINENUMBER, 
    L_QUANTITY, 
    L_EXTENDEDPRICE, 
    L_DISCOUNT, 
    L_TAX, 
    L_RETURNFLAG, 
    L_LINESTATUS, 
    L_SHIPDATE, 
    L_COMMITDATE, 
    L_RECEIPTDATE, 
    L_SHIPINSTRUCT, 
    L_SHIPMODE, 
    L_COMMENT
FROM final
ORDER BY L_SHIPDATE

) AS source
    ON target.L_ORDERKEY = source.L_ORDERKEY
    WHEN MATCHED THEN
        UPDATE SET 
            target.L_PARTKEY = source.L_PARTKEY,
			target.L_SUPPKEY = source.L_SUPPKEY,
			target.L_LINENUMBER = source.L_LINENUMBER,
			target.L_QUANTITY = source.L_QUANTITY,
			target.L_EXTENDEDPRICE = source.L_EXTENDEDPRICE,
			target.L_DISCOUNT = source.L_DISCOUNT,
			target.L_TAX = source.L_TAX, 
			target.L_RETURNFLAG = source.L_RETURNFLAG, 
			target.L_LINESTATUS = source.L_LINESTATUS, 
			target.L_SHIPDATE = source.L_SHIPDATE, 
			target.L_COMMITDATE = source.L_COMMITDATE, 
			target.L_RECEIPTDATE = source.L_RECEIPTDATE, 
			target.L_SHIPINSTRUCT = source.L_SHIPINSTRUCT, 
			target.L_SHIPMODE = source.L_SHIPMODE, 
			target.L_COMMENT = source.L_COMMENT
			WHEN NOT MATCHED THEN
        INSERT (L_ORDERKEY, L_PARTKEY, L_SUPPKEY, L_LINENUMBER, L_QUANTITY, L_EXTENDEDPRICE, L_DISCOUNT, L_TAX, L_RETURNFLAG, L_LINESTATUS, L_SHIPDATE, L_COMMITDATE, L_RECEIPTDATE, L_SHIPINSTRUCT, L_SHIPMODE, L_COMMENT)
		VALUES (source.L_ORDERKEY, source.L_PARTKEY, source.L_SUPPKEY, source.L_LINENUMBER, source.L_QUANTITY, source.L_EXTENDEDPRICE,  source.L_DISCOUNT, source.L_TAX, source.L_RETURNFLAG, source.L_LINESTATUS, source.L_SHIPDATE, source.L_COMMITDATE, source.L_RECEIPTDATE,  source.L_SHIPINSTRUCT, source.L_SHIPMODE, source.L_COMMENT);
		
    RETURN ''Procedure completed successfully'';
    END;
';