name: CircleCI Workflow API Trigger

on:
  pull_request:
    types: [opened, reopened]
    branches: [main, develop]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Build
        run: |
          curl --request POST \
            --url https://circleci.com/api/v2/project/gh/rampotla586/ut_de_framework/pipeline \
            --header 'Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{"parameters":{"github_trigger":true},"branch":"${{ github.head_ref }}"}'
